# =============================================================================
# CityWars Siege Configuration
# Este archivo gestiona todo el sistema de asedios entre ciudades
# =============================================================================

# Configuración Principal de Asedios
siege:
  # Economía del asedio
  currency: "jp"  # Moneda utilizada para los asedios
  cost: 1000.0   # Costo para iniciar un asedio

  # Duración y tiempo
  duration: 1800  # Duración del asedio en segundos (30 minutos)
  loot-phase-duration: 300  # Duración de la fase de saqueo en segundos (5 minutos)
  cooldown: 3600000  # Cooldown entre asedios en milisegundos (1 hora)

  # Requisitos para iniciar asedio
  minimum-online-percentage: 0.3  # 30% de ciudadanos deben estar online

  # Estandarte de asedio
  flag-material: "RED_BANNER"  # Material del estandarte de asedio
  flag-display-name: "&c&lEstandarte de Asedio"
  flag-lore:
    - "&7Un estandarte que marca el"
    - "&7inicio de un asedio épico"
    - ""
    - "&cClick derecho para colocar"

  # Efectos visuales
  firework-interval: 30  # Intervalo de fuegos artificiales en segundos
  particles:
    enabled: true
    flame-count: 50
    smoke-count: 20
    radius: 2.0

  # Sonidos
  sounds:
    siege-start: "ENTITY_WITHER_SPAWN"
    flag-captured: "ENTITY_ENDER_DRAGON_GROWL"
    siege-end: "ENTITY_EXPERIENCE_ORB_PICKUP"
    firework: "ENTITY_FIREWORK_ROCKET_LAUNCH"

# Configuración de Recompensas
rewards:
  # Recompensas por victoria
  victory:
    enabled: true
    treasury-percentage: 0.5  # 50% del tesoro de la ciudad derrotada
    individual-bonus: 100.0   # Bonus individual para participantes
    currency: "jp"

    # Recompensas adicionales
    experience: 500
    items:
      enabled: false
      list:
        - "DIAMOND:5"
        - "GOLD_INGOT:10"
        - "EMERALD:3"

  # Compensaciones por derrota
  defeat-compensation:
    enabled: true
    percentage: 0.1  # 10% de compensación del costo del asedio

  # Recompensas por participación
  participation:
    kill-reward: 50.0      # Recompensa por eliminar enemigo
    flag-capture-reward: 200.0  # Recompensa por capturar bandera
    defense-bonus: 25.0    # Bonus por defender exitosamente

# Configuración de Protecciones
protections:
  # Flags que se desactivan durante el asedio
  disabled-during-siege:
    - "PREVENT_BLOCK_BREAK"
    - "PREVENT_BLOCK_PLACE"
    - "PREVENT_INTERACTION"
    - "PREVENT_EXPLOSION"

  # Flags que se activan durante el asedio
  enabled-during-siege:
    - "PVP"

  # Areas protegidas dentro de la ciudad
  safe-zones:
    enabled: true
    spawn-protection-radius: 10  # Radio de protección del spawn
    hospital-protection: true    # Protección de hospitales

  # Límites de destrucción
  destruction-limits:
    max-blocks-per-player: 100
    forbidden-blocks:
      - "BEDROCK"
      - "BARRIER"
      - "COMMAND_BLOCK"
      - "STRUCTURE_BLOCK"

# Configuración de Participantes
participants:
  # Límites de participación
  max-attackers-per-siege: 20
  max-simultaneous-sieges: 3

  # Restricciones
  level-requirement: 10  # Nivel mínimo para participar
  playtime-requirement: 7200  # Tiempo mínimo jugado en segundos (2 horas)

  # Penalizaciones por abandono
  abandon-penalty:
    enabled: true
    currency-loss: 100.0
    cooldown-extension: 1800000  # 30 minutos adicionales

# Configuración de Estados de Asedio
siege-states:
  preparation:
    duration: 300  # 5 minutos de preparación
    announce-interval: 60  # Anunciar cada minuto

  active:
    update-interval: 30  # Actualizar estado cada 30 segundos
    warning-times: [300, 180, 60, 30, 10]  # Advertencias de tiempo restante

  loot-phase:
    grace-period: 30  # 30 segundos de gracia al inicio
    protect-storage: false  # Si proteger contenedores durante saqueo

# Configuración de Validaciones
validations:
  # Verificaciones de territorio
  territory:
    min-distance-from-spawn: 100  # Distancia mínima del spawn de la ciudad
    max-distance-from-border: 50  # Distancia máxima del borde de la ciudad
    forbidden-biomes: []  # Biomas donde no se puede asediar

  # Verificaciones de ciudad
  city:
    min-age-days: 7  # Edad mínima de la ciudad en días
    min-members: 3   # Mínimo de miembros para ser asediada
    max-protection-level: 5  # Nivel máximo de protección

  # Verificaciones de jugador
  player:
    ban-check: true  # Verificar si el jugador está baneado
    mute-check: false # Verificar si el jugador está muteado
    jail-check: true  # Verificar si el jugador está en la cárcel

# Configuración de Notificaciones
notifications:
  # Configuración de títulos
  titles:
    enabled: true
    fade-in: 10
    stay: 70
    fade-out: 20

  # Mensajes del sistema
  messages:
    prefix: "&8[&4Asedio&8] &r"

    # Inicio de asedio
    siege-started-attacker: "&e¡{attacker} ha iniciado un asedio contra {defending_city}!"
    siege-started-defender: "&c¡Tu ciudad está bajo ataque por {attacking_city}!"
    siege-started-title-defender: "&c¡BAJO ATAQUE!"

    # Captura de bandera
    flag-captured: "&6¡{player} ha capturado la bandera! ¡Fase de saqueo iniciada!"
    flag-captured-title: "&6¡BANDERA CAPTURADA!"

    # Fin de asedio
    siege-victory: "&a¡{attacking_city} ha conquistado {defending_city}!"
    siege-defeat: "&c¡{defending_city} ha defendido exitosamente su ciudad!"
    siege-cancelled: "&7El asedio ha sido cancelado por un administrador."

    # Protecciones
    protections-disabled: "&c¡Defensas desactivadas!"
    protections-restored: "&a¡Defensas restauradas!"

    # Recompensas
    reward-transfer: "&6¡{attacking_city} ha saqueado {amount} del tesoro de {defending_city}!"
    individual-reward: "&a¡Has recibido {amount} {currency} por tu participación!"

    # Errores y validaciones
    not-in-city: "&cDebes pertenecer a una ciudad para iniciar un asedio."
    city-under-siege: "&cTu ciudad está bajo asedio y no puede atacar."
    target-under-siege: "&cEsta ciudad ya está bajo asedio."
    insufficient-funds: "&cNecesitas {amount} {currency} para iniciar un asedio."
    cooldown-active: "&cDebes esperar antes de atacar esta ciudad nuevamente."
    insufficient-online: "&cLa ciudad debe tener al menos {percentage}% de sus ciudadanos conectados."
    flag-outside-territory: "&cDebes colocar el estandarte dentro del territorio enemigo."

# Configuración de Base de Datos (para persistencia)
database:
  enabled: false
  type: "yaml"  # yaml, sqlite, mysql

  # Configuración MySQL (si se usa)
  mysql:
    host: "localhost"
    port: 3306
    database: "citywars_sieges"
    username: "user"
    password: "password"

  # Archivos de datos
  files:
    active-sieges: "active-sieges.yml"
    cooldowns: "cooldowns.yml"
    siege-history: "siege-history.yml"

# Configuración de Logging
logging:
  enabled: true
  level: "INFO"  # ALL, INFO, WARNING, SEVERE
  log-file: "sieges.log"

  # Eventos a registrar
  log-events:
    siege-start: true
    siege-end: true
    flag-capture: true
    player-death: true
    reward-distribution: true
    admin-intervention: true

# Configuración de Comandos
commands:
  # Aliases para comandos
  aliases:
    siege: ["asedio", "war", "attack"]
    cancel-siege: ["cancelsiege", "stopsiege"]
    siege-info: ["siegeinfo", "si"]

  # Cooldowns de comandos
  command-cooldowns:
    siege: 5  # 5 segundos entre usos
    siege-info: 1  # 1 segundo entre usos

# Configuración de Integraciones
integrations:
  # Integración con otros plugins
  dynmap:
    enabled: false
    show-siege-markers: true
    marker-icon: "redflag"

  discord:
    enabled: false
    webhook-url: ""
    notify-siege-events: true

  # Hooks de eventos personalizados
  custom-events:
    enabled: true
    call-api-events: false

# Configuración de Rendimiento
performance:
  # Optimizaciones
  async-operations: true
  cache-enabled: true
  cache-size: 100

  # Límites de recursos
  max-particles-per-siege: 200
  max-sounds-per-siege: 50
  cleanup-interval: 300  # Limpiar cada 5 minutos

  # Configuración de hilos
  thread-pool-size: 2
  async-save-interval: 600  # Guardar async cada 10 minutos

# Configuración de Mundos
worlds:
  # Mundos permitidos para asedios
  allowed-worlds:
    - "world"
    - "world_nether"
    # - "world_the_end"  # Comentado para deshabilitar

  # Configuraciones específicas por mundo
  world-settings:
    world:
      siege-enabled: true
      max-simultaneous: 5

    world_nether:
      siege-enabled: true
      max-simultaneous: 2
      damage-multiplier: 1.5

# Configuración de Backup y Recuperación
backup:
  enabled: true
  interval: 1800  # Cada 30 minutos
  max-backups: 48  # Mantener 48 backups (24 horas)
  compress: true

  # Restauración automática
  auto-restore:
    enabled: false
    conditions:
      - "server-crash"
      - "data-corruption"

# Configuración Experimental
experimental:
  enabled: false

  # Características en desarrollo
  siege-seasons: false
  dynamic-rewards: false
  ai-defenders: false
  siege-tournaments: false